name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: ./
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag db:$(date +%s)
